Remove the trailing semicolon, to get rid of double semicolons in produced videoinfo.h.
The file `videoinfo.h` contains the following line:

    Glib::RefPtr<Gst::Caps> to_caps() const;;

This is, because the file `videoinfo.hg` contains a semicolon in line 69. Remove it, and than the compiler doesn't complain about extra semicolons:

/usr/include/gstreamermm-1.0/gstreamermm/videoinfo.h:547:43: error: extra ‘;’ [-Wpedantic]
   Glib::RefPtr<Gst::Caps> to_caps() const;;

I'm using g++-8.1.0 and the debian testing package of gstreamermm (1.10.0).