Removed gdpdeplay and gdppay plug-ins because they cause strange warnings
2008-12-14  José Alburquerque  <jaalburqu@svn.gnome.org>

	* gstreamerbase/src/Makefile_list_of_hg.am_fragment: Removed gdpdeplay
	and gdppay plug-ins because they cause strange warnings when their
	wrap_new() methods are registered in GstBase::wrap_init():
	* Makefile.am: Build examples before tests.

	Discovered that the media player example only works outside of jhbuild
	now.  The error when attempting to play a media file in jhbuild
	environment:

	Error: Missing element 'input-selector' - check your GStreamer
	installation.

svn path=/gstreamermm/trunk/; revision=1855